### ISSUE TITLE
Consolidate notifications for extensions

### ISSUE THREAD

**Issue by mrshu** [tosdr/browser-extensions#10]
Per @xMartin's suggestion I'd like to start a discussion on how should notifications in tosdr's extensions (they get triggered when user load a badly rated site [that is rating D or E]) behave.

Let me start by the description of the current state:
- On Firefox the user will see the notification when he loads the site and then when he loads the site after more than 13 days.
- On Chrome the feature is broken at this time but my pull request (https://github.com/shybyte/tos-checker/pull/19) should fix it. The code has pretty much the same logic as the one in Firefox extension with a small exception: the user will see the extension next time after 7 days.
- On Opera the code is precisely the same in this regard as the Chrome one. Since these browsers use the same engine now their extensions APIs differ minimally and it might be a good idea to actually use the same codebase for both of their extensions (my patch for Chrome will work on Opera too).
- On Safari there is no such functionality present at the moment and this state was the impetus for starting this discussion (https://github.com/tosdr/tosdr-safari/pull/7). Let me thus share my view over notifications.

There are basically three requirements notifications should meet:
- The notification window should always link to the service's review on tosdr.org
- The user should see the notification every time he or she loads the website in one day/browser session [1]
- There should be a setting to turn this functionality off. In a perfect world it would be possible to turn it off for a specific website.

Please do let me know what you think so that I can continue with the Safari extension and maybe reflect this discussion in other extensions.

[1] This part is open for discussion, I'd personally be OK with once per day or once per browser session, though I agree that the later might be a bit problematic in case of YouTube for example.

**Comment by JustinBack** [comment]
I suppose since notifications are implemented, this is stale?
