### ISSUE TITLE
Do not load webpages in the Extension's popup Window - because as soon as it closes, entered content is lost. 

### ISSUE THREAD

**Issue by NA0341** [tosdr/browser-extensions#101]
This happens with the function »Request <service> to be added«.

**Steps to reproduce:**

+ Enter a website which is not rated yet.
+ Open the tl;dr Extension popup & click »Request <service> to be added«.
+ Enter info in the form fields & then click anywhere outside the popup -» it closes.
+ The next time you open the form, the info you wrote is gone.

Cheers, NA0341.

PS: Please also someone update the Issue templates. Because https://tosdr.org/en/downloads#bug leads nowhere but to the dl page.

**Comment by JustinBack** [comment]
Thanks for reporting this,

Mind giving us some more info about:

- The Browser running including Version
- The OS
- Version of the extension

In firefox I cannot reproduce this as the button opens a new window as it should

**Comment by NA0341** [comment]
Sure (=

Extension Version is 4.1.2 from Chrome Webstore
Browser is Vivaldi 6.2.3105.54 (Stable channel) on Manjaro Linux (Arch Linux) with GNOME 44.4 running Wayland

This behaviour happens since I use the extension (~1 Year)

![Screenshot from 2023-10-05 14-09-25](https://github.com/tosdr/browser-extensions/assets/26059513/939614df-7432-425e-9745-6d5d5601fa57)

![image](https://github.com/tosdr/browser-extensions/assets/26059513/542f8495-6513-4af1-8186-586e313a2e3a)

**Comment by JustinBack** [comment]
Hmm this is something I cannot reproduce in chrome itself so its a vivaldi-related bug.

Though In chrome nothing happens when I click the button, possibly due to blocking embedding the ToS;DR website into the iframe, vivaldi does not and thus the page opens in the popup.


While I don't have an immediate fix on hand, you can rightclick the button in the meantime to open it in a new tab.

**Comment by ptgms** [comment]
Closed due to this being part of the old extension that is no longer supported.
