### ISSUE TITLE
userscript

### ISSUE THREAD

**Issue by KraXen72** [tosdr/browser-extensions#102]
Please release a version as a [userscript](https://www.wikiwand.com/en/Userscript) as well, alongside the extension versions. Thanks!

**Comment by ptgms** [comment]
if we were to make a userscript version, we'd need to manipulate the DOM in a way to show the grade of each website. also, itll be hard to use one of the libraries we use (like jszip) to download a database.

this is currently out of scope, but help is always appreciated if someone wants to have a go at it :)

**Comment by KraXen72** [comment]
hmm, that's true - i forgot userscripts can't make popups easily. i guess a window.open could work, but after this justification, i'm fine with installing the extension. can't wait for a build of the rewritten version! thanks for all your work so far.
