### ISSUE TITLE
Updating data from tosdr.org (and no user-browsing leaking)

### ISSUE THREAD

**Issue by hugoroy** [tosdr/browser-extensions#12]
Continues from: https://github.com/tosdr/tosdr.org/issues/36

All browser extensions should be designed in a way that the hosters of tosdr.org **cannot** see users browsing activities. So it is important that the browser extensions are designed in a way that they don't make a request to tosdr.org for every  website visited to get the class-rating.

Discuss here the concept or specification relevant to all browsers.

Please open relevant issues in each browser extension repositories, if there are specific problems or bugs.

**Comment by michielbdejong** [comment]
This was closed accidentally by the history merge, but this is an issue that was actually resolved, the extension now only access https://tosdr.org/api/1/all.json. We're already starting to notice the reduction of traffic in 5apps stats.
