### ISSUE TITLE
extension has no function

### ISSUE THREAD

**Issue by davidak** [tosdr/browser-extensions#14]
I installed the extension, but it has no function.

![screenshot from 2018-07-15 21-09-10](https://user-images.githubusercontent.com/91113/42737423-7b7869bc-8873-11e8-9436-e0d765a01088.png)

This is how it looks when i have https://github.com/tosdr/browser-extensions/issues/13 open. That issue might also be the reason.

---

Chromium 65.0.3325.162

**Comment by shybyte** [comment]
@michielbdejong @piks3l It seems that the format of the API response (like in https://tosdr.org/services/youtube.json) has changed. For example, there is no **url** attribute anymore but an **urls** attributes.
Is this an intended change?
Is there another API endpoint that is compatible with the old format?
Is the new format documented and stable?

**Comment by shybyte** [comment]
@michielbdejong  @piks3l @tosdr/phoenix @tosdr/browser-extensions-developers 
This API changes breaks probably not only the chrome extension, but others too, like for example https://github.com/tosdr/tosdr-firefox/issues/51.

**Comment by michielbdejong** [comment]
Looking at https://github.com/tosdr/tosdr.org/wiki/Specification:-services/_history it seems this API change had already happened before May 2013, and also it makes no sense to have a single `.url` field, many services have multiple domain names, so `.urls` is better. I think we should fix it in all browser extensions, like @floSoX already did in #17.
