### ISSUE TITLE
One codebase for all browser extensions (+ publishing account ?)

### ISSUE THREAD

**Issue by shybyte** [tosdr/browser-extensions#18]
There are currently multiple codebases for the several browser extensions (ordered by freshness):

* https://github.com/tosdr/tosdr-firefox 
* https://github.com/tosdr/tosdr-chrome 
* https://github.com/tosdr/tosdr-safari
* https://github.com/tosdr/tosdr-ie

Nowadays, thanks to the common WebExtensions API in browsers, it should be possible to use one codebase for Chrome, Firefox and Edge (and with some small modifications, maybe even Safari). 

https://github.com/tosdr/tosdr-firefox is the most up-to-date extension.

Therefore I guess, we should use tosdr-firefox as codebase for the other extensions, starting with the chrome extension. (Probably tosdr-firefox works already in chrome!?)

@tosdr/browser-extensions-developers @AbdullahDiaa @michielbdejong 

* What do you think? 
* Is there an interest in having up-to-date  browser extensions for tosdr?
* Are there other extension efforts, I don't know of?
* How can we manage publishing? https://chrome.google.com/webstore/detail/terms-of-service-didn%E2%80%99t-r/hjdoplcnndgiblooccencgcggcoihigg/reviews?hl=en for example is published from my private google account, which is suboptimal, because only I can publish it. We could create an special official tosdr account and enable "Group Publishing" for it ( https://developer.chrome.com/webstore/publish).

**Comment by michielbdejong** [comment]
:100: Thanks for bringing this up, @shybyte !

I'll start by creating a group account for Chrome Web Store and see if I can publish our WebExtension on there! If it all works, we should indeed rename tosdr-firefox to tosdr-webextension or similar, and deprecate the other browser-specific ones. Even if it requires small changes, it probably makes sense to merge these repositories into one, and maybe e.g. build the Safari one with a special build step where necessary.

**Comment by michielbdejong** [comment]
>  (Probably tosdr-firefox works already in chrome!?)

Yes, with some minor tweaks, see https://github.com/tosdr/tosdr-firefox/pull/58

@shybyte can you add me to https://chrome.google.com/webstore/detail/terms-of-service-didn%E2%80%99t-r/hjdoplcnndgiblooccencgcggcoihigg?

**Comment by shybyte** [comment]
@michielbdejong  I would like to do this, but  I don't know if this is so easy. In https://developer.chrome.com/webstore/publish is stated: 

> Set up Group Publishing
You can share ownership of your items in Google Chrome Web Store with other developers by setting up group publishing. With group publishing, you can add developers to a Google Group, who can then act on your behalf. **They'll have access to all the items you own and can make any changes to them that you can make**.

Maybe I understand this wrong, but **access to all the items you own** seems to be not want I want.(???) 
Maybe it's better, you create an official Tosdr account and I deprecate the old published extension? 
Or is there a way to just share the Tosdr-extension, but not all my stuff? 
It would be also good and increase trust if the todsd-extension would be published from an official looking email and not from myemail@googlemail.com.

**Comment by michielbdejong** [comment]
True! I had no published plugins in my account, so I sacrificed my developer account and created a Publisher group containing the two of us, for now. You should now have access to it, and should be able to move the extension into the publishing group, hopefully without disrupting it? And that should then hopefully give me permission to publish an update. We should check what the publisher profile looks like once it's moved (the group is [https://groups.google.com/forum/#!forum/tosdr-chromewebstore-publishers](https://groups.google.com/forum/#!forum/tosdr-chromewebstore-publishers)).

Thanks!
Michiel.

**Comment by shybyte** [comment]
@michielbdejong  I have moved the extension to tosdr-chromewebstore-publishers.I guess it worked without problems.

**Comment by michielbdejong** [comment]
Done! Deployed version 2.0.0 to 5% of users. Will slowly increment that percentage and keep an eye on user feedback.
