### ISSUE TITLE
Undefined point icons

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/browser-extensions#20]
See http://tosdr.github.io/browser-extensions/popup/?url=http://google.com

It's because it retrieves e.g. https://tosdr.org/points/1040.json which has no tosdr.point field (it has tosdr.case now).

It should retrieve https://tosdr.org/api/1/service/google.json and use pointsData from there (then it gets all the data about Google in one api request)

**Comment by michielbdejong** [comment]
I'm unsure if any of the published browser extensions actually use the popup from this repo directly? Will find that out, then fix this issue in the place where fixing it actually affects the deployed extensions, and deprecate other copies of the same code.

**Comment by JustinBack** [comment]
Fixed in earlier version.
