### ISSUE TITLE
Repeat notifications less often?

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/browser-extensions#26]
Notifications are set to repeat [after 7 days](https://github.com/tosdr/browser-extensions/blob/master/src/background.js#L19), maybe that's a bit too often.

Thanks to https://addons.mozilla.org/en-US/firefox/addon/terms-of-service-didnt-read/reviews/1186162 for reporting this!

**Comment by michielbdejong** [comment]
Maybe it should count 7 days since you last visited youtube, instead of 7 days since you last saw the ToS;DR warning about youtube. That would mean that if you visit certain sites on a daily basis, you would only see the warning after e.g. you come back from holidays.

**Comment by dmose** [comment]
This is particularly frustrating for those of us who restart browsers with session restore regularly, which causes notifications for open tabs to be re-sent.
