### ISSUE TITLE
Remove unused JavaScript libraries

### ISSUE THREAD

**Issue by oslego** [tosdr/browser-extensions#30]
The [`underscore-min.js`](https://github.com/tosdr/browser-extensions/blob/master/src/popup/js/underscore-min.js) library and [`bootstrap.min`](https://github.com/tosdr/browser-extensions/blob/master/src/popup/js/bootstrap.min.js) library are not referenced in the `manifest.json` file, nor do they seem to be used anywhere in the web extension code.

Can these libraries be safely removed from the repository?

**Comment by JustinBack** [comment]
Those are needed for the popup and settings page respectively
