### ISSUE TITLE
Escape service name in li element

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/browser-extensions#37]
See https://github.com/tosdr/browser-extensions/blob/2b9474e862359a64f61aede5c21b74dad1dbfbbb/src/popup/js/popup.js#L102 - although `service.name` and `p.id` come from our database, let's keep them unescaped in the database, and then escape those strings here.

Thanks to Xena from Firefox extension review for reporting this!

**Comment by JustinBack** [comment]
Fixed in 89e56898271bc1ec6404d46b12f100a9ca636e77
