### ISSUE TITLE
Mozilla Firefox mobile browser extension

### ISSUE THREAD

**Issue by Peepo1** [tosdr/browser-extensions#40]
The Mozilla Firefox app on mobile doesn't have the extension in the side bar. I have other extensions like 1 password and privacy badger that can be selected and viewed but Tosdr is not located here after downloading it, preventing the cases and grade to be seen.

![20200824_135209](https://user-images.githubusercontent.com/58347559/91084957-5a7a8480-e612-11ea-9a85-4b7b3b47c49d.jpg)
![Screenshot_20200824-135046_Firefox](https://user-images.githubusercontent.com/58347559/91084964-5cdcde80-e612-11ea-8373-7c6588b18fe5.jpg)

**Comment by JustinBack** [comment]
Firefox mobile is not supported.
