### ISSUE TITLE
Keeps reffering to the Google Group

### ISSUE THREAD

**Issue by DrKJeff16** [tosdr/browser-extensions#41]
# The Extension keeps linking to the Google Group, which is pretty much deprecated.-
Browser: Firefox, *but judging by the code it doesn't really matter.*

![Extension-Outdated](https://user-images.githubusercontent.com/72052712/101969482-27bcc200-3bea-11eb-978f-de896420fd53.jpg)

## Maybe we ought to switch the text so it reffers to the [Phoenix Site](https://edit.tosdr.org)/[*Why so many services lack a Rating?*](https://tosdr.org/classification.html#status).

**Comment by JustinBack** [comment]
Fixed in 393df37
