### ISSUE TITLE
Should try to reload services.json after a while, if it failed earlier.

### ISSUE THREAD

**Issue by nilclass** [tosdr/browser-extensions#5]
Today I started my browser, then noticed that my wifi was turned off. Later I noticed, that none of the sites that I visited showed any ToS;DR Icon in the address bar. When inspecting the extension's background view, it turned out that it tried to load "services.json" all the way in the beginning, when the browser started, but didn't retry later, when I was actually connected.

So my suggestion would be, that if the service list failed to load earlier, simply to retry as soon as a site's rating is being looked up.

**Comment by michielbdejong** [comment]
This was closed accidentally by the history merge.

**Comment by Vinnl** [comment]
Whoops, didn't realise that that would happen, sorry.
