### ISSUE TITLE
Notification link broken

### ISSUE THREAD

**Issue by turtlebasket** [tosdr/browser-extensions#54]
**Describe the bug**
When ToS;DR gives me an alert about a website's ToS, the notification's link is broken.
For example: when using Google services, the warning notification sent me to https://beta.tosdr.org/service/google - which gave me a 404. It was working earlier last week, so it could be that the website's directory paths have changed or something like that. If that's the case, then I suppose this is just a note to update the extension.

**To Reproduce**
1. Get a ToS;DR notification to pop up for any site (presumably one with a questionable tos, in my case it was Google)
2. Click on the notification

**Expected behavior**
Clicking on the ToS;DR notification should take me to the page for 

**Screenshots**
![image](https://user-images.githubusercontent.com/32886427/104681568-7a851000-56a7-11eb-8caf-a7b9c95e77c5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Firefox
 - Version: 84.0.2

**Extension (please complete the following information):**
- Version: 2.0.1
- Packed? Yes (from addons.mozilla.org)

**Comment by JustinBack** [comment]
Thanks for reporting this, The bug has been fixed with Release 3.0.0 in b855b01c0d626eba4bbd9c7739fda37330ea3990
