### ISSUE TITLE
Links open as about:blank

### ISSUE THREAD

**Issue by ghost** [tosdr/browser-extensions#56]
**Expected behavior**
A link clicked in the extension's panel will open, either in the tab the user is on when the extension panel is opened, or a new tab.

**Describe the bug**
Clicking most (see 'additional context' section) links in the extension panel lead only to about:blank in a new tab.

**To Reproduce**
1. Visit site of a service in the ToS;DR database
2. Click on the extension icon to open the pane
3. Hover over the ToS;DR logo or the point list items or the Terms links or the contribute/donate buttons and observe the browser status bar at the bottom of the screen indicating the correct URL the link leads to.
4. Click on any of these links and observe that a new tab has opened but instead of the expected URL, it is about:blank.

**Desktop (please complete the following information):**
 - OS: [PureOS](https://tracker.pureos.net/w) (basically Debian)
 - Browser: Firefox
 - Version: 78.6.1esr
Build ID 	20210105204613

**Extension (please complete the following information):**
- Version: v3.2.1, jid0-3GUEt1r69sQNSrca5p8kx9Ezc3U@jetpack
- Downloaded from Firefox webstore

**Additional context**
The 'request a service' link for sites not yet in the database is an exception; it does work as expected.
Beta version of the extension is also installed but was disabled before bug was first noticed.

**Comment by JustinBack** [comment]
Cannot reproduce this on 84.0.2. What extensions do you have installed? Its possible another hijacks the links such as an adblocker or privacy protection addons
