### ISSUE TITLE
about:addons panel occasionally pops open to the 

### ISSUE THREAD

**Issue by jonohewitt** [tosdr/browser-extensions#60]
Occasionally while browsing and after updating firefox, a new about:addons tab will open by itself and take focus. The Terms of Service; Didn’t Read add-on page is showing and the permissions tab is selected. None of the tickboxes are selected. This has started happening since adding the feature to disable notifications.

**To Reproduce**
It has randomly happened a few times now with different computers. I haven't noticed a guaranteed reproduction so far but immediatley after Firefox updates seems to be reoccuring.

**Expected behavior**
No tab self opening

**Desktop (please complete the following information):**
 - OS: macOS 11.1
 - Browser: Firefox
 - Version: 85.0

**Extension (please complete the following information):**
- Version: 4.0.3 from Mozilla Add-ons

**Comment by JustinBack** [comment]
https://github.com/tosdr/browser-extensions/blob/854d54eec8278193a4990295583887dc5918e431/src/background.js#L128-L130

This could be how firefox handles extension installation. If it fires onInstallation each time you update firefox this is intended behaviour. However while randomly browsing this should not happen at all.

I'll investigate this

**Comment by NatoBoram** [comment]
Ah, I'm relieved I'm not the only one with this problem. I'll be disabling the extension until this is fixed.

**Comment by JustinBack** [comment]
This happens when firefox is updated to a new version as well.

> Fired when the extension is first installed, when the extension is updated to a new version, and when the browser is updated to a new version.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onInstalled

I'll implement an `if` with the installation type to prevent this on browser updates.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/OnInstalledReason
