### ISSUE TITLE
clear API cache not working

### ISSUE THREAD

**Issue by pederdm000** [tosdr/browser-extensions#61]
**Describe the bug**
clear API cache button not working correctly 

**To Reproduce**
1. Go to '...'Terms of Service; Didn’t Read options on Firefox add-on 
2. Click on clear API cache
3. restart Firefox 
4. old cache still there

**Expected behavior**
API cache not cleared even after browser restart 

**Desktop (please complete the following information):**
 - OS:  windows 10 pro
 - Browser: Firefox
 - Version: 85.0 (64-bit)

**Extension (please complete the following information):**
- Version: [e.g. 4.0.3]
- Packed? [Yes]

**Additional context**

- [x] I make sure not to use an API override
- [x] I make sure not to use a shield override
- [x] I make sure not to use an updatecheck override

**Comment by ptgms** [comment]
Closed due to this being part of the old extension that is no longer supported.
