### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by maria431** [tosdr/browser-extensions#66]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Console Log**
If applicable, add console logs by enabling the `Debug` Option in `Options` -> `Advanced Mode`

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

- [ ] I make sure not to use an API override
- [ ] I make sure not to use a shield override
- [ ] I make sure not to use an updatecheck override

**Comment by JustinBack** [comment]
The purpose of this template is to be filled out :-)
