### ISSUE TITLE
If notifications are hidden without opening them, the next time one is opened, the 'backlog' of all the hidden ones will also open

### ISSUE THREAD

**Issue by ghost** [tosdr/browser-extensions#67]
**Describe the bug**
The title of this bug. I'll also note that Firefox' push notifications are handled through openDesktop / GNOME's interface, and that when I say they open, I mean as a series of new tabs in the most-recently-viewed browser window.

**To Reproduce**
1. Go to a site whose ToS raise serious issues
2. Observe the push notify saying so but don't open it, hide it (for me this involves hitting an 'x' in the corner).
3. Do this a certain number of times. One of the times, click on the notify to open it instead.

**Expected behavior**
Only the notification I clicked on should open

**Screenshots**
Not easily screenshottable. I can show the notifications pane in GNOME if that would help.

**Console Log**
If applicable (not in this case probably?), add console logs by enabling the `Debug` Option in `Options` -> `Advanced Mode`

**Desktop (please complete the following information):**
 - OS: PureOS (aka Debian Testing)
 - Browser: Firefox
 - Version: about:support sez: 78.7.0esr, Build ID 20210119174753

**Extension (please complete the following information):**
- Version: about:addons sez: 4.0.3
- Packed? Yes, downloaded from Store]

**Additional context**
'serious issues' domains tested include Apple, Youtube, and a couple others not immediately coming to mind.

- [x] I make sure not to use an API override
- [x] I make sure not to use a shield override
- [x] I make sure not to use an updatecheck override

**Comment by JustinBack** [comment]
I see if I can fix it in the next patch

**Comment by ArloJamesBarnes** [comment]
I see the label of that commit is 4.0.6, but I have that version and still experience this problem

**Comment by JustinBack** [comment]
Interesting, guess https://github.com/tosdr/browser-extensions/commit/b0032b99f431e4eb7a10fea61520d594f88b7d9a did not fix it then, I'll target a higher version

**Comment by GameDungeon** [comment]
I'm on brave, and that most definitely happens. And I've found it's a persistent backlog that just grows larger as I use the browser. After doing some research I had a least 40 tabs open every time I click the notification.
