### ISSUE TITLE
Randomly opens the options diolog?

### ISSUE THREAD

**Issue by Darkwolf1515** [tosdr/browser-extensions#68]
**Describe the bug**
Randomly, your exentsion will open its setting page, unprompted, without any of my input.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: Firefox
 - Version: 85.0

**Extension (please complete the following information):**
- Version: 4.04
- Packed? Yes

**Comment by JustinBack** [comment]
This only happens during installation or updates. See #60
