### ISSUE TITLE
Close button... not working

### ISSUE THREAD

**Issue by MartinHeywang** [tosdr/browser-extensions#69]
**Describe the bug**
The close button of the extension popup doesn't work whenever the terms of services of the current site aren't available yet.

**To Reproduce**
1. Open Firefox Developer Edition
1. Go to a website where the terms of services aren't revised yet. (for example: [Undraw](https://undraw.co/))
2. Click on the ToS;Dr extension icon to open the popup.
3. Click on the close icon
4. See that the popup isn't closed

**Expected behavior**
The popup should be closed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox Developer Edition
 - Version: 86.0b5 (64 bits)

**Extension (please complete the following information):**
- Version: 4.0.4
- Packed? don't know, download directly from [ToS;Dr](tosdr.org)

**Comment by JustinBack** [comment]
Good call! I'll fix this in the next patch version
