### ISSUE TITLE
Firefox extension isn't working

### ISSUE THREAD

**Issue by davidncali** [tosdr/browser-extensions#73]
Trying to use the TOSDR extension on Firefox however every site I go to says the same thing:  This service is not rated yet.  Request (any website) to be added.

![Clipboard01](https://user-images.githubusercontent.com/71229495/107972666-14dcba00-6fac-11eb-8000-d815a05ff7f0.jpg)

**Comment by JustinBack** [comment]
I'll investigate this!

**Comment by gigamicro** [comment]
I'm getting a similar error; the API seems to be timing out.
(On chrome; icon still shows rating)

**Comment by Xethron** [comment]
I'm having the same issue. All sites show as not rated.

**Comment by JustinBack** [comment]
A temporary solution would be to override the API endpoint until we fix the defective routing.

![image](https://user-images.githubusercontent.com/40178814/108598597-c73ac580-738e-11eb-98ab-1041f8f7838e.png)

**Comment by davidncali** [comment]
What should we override the API with?  The API's that are in the app don't resolve.  Do you have new API's for us to enter into the boxes of the app?

**Comment by JustinBack** [comment]
The ones in the image above. I'll fix the routing momentarily, it will take a while to propagate though.

API Endpoint Override:
```
https://tosdr.org/api/v1/service/
```

Update API Endpoint Override:
```
https://tosdr.org/api/updatecheck/
```

**Comment by JustinBack** [comment]
See the artifacts in v4.0.6

https://github.com/tosdr/browser-extensions/releases/tag/4.0.6


https://github.com/tosdr/browser-extensions/releases/download/4.0.6/firefox.xpi
https://github.com/tosdr/browser-extensions/releases/download/4.0.6/chrome.zip

AMO will be released shortly.

Chrome takes a while to update, the propagation would have worked so far then.

**Comment by paulverbeke** [comment]
on Firefox, with Tosdr 4.0.6, icon still shows rating but popup still timing out. 
![image](https://user-images.githubusercontent.com/6412153/109795163-e64f1800-7c16-11eb-90f4-868dbddc2497.png)
Overriding the API endpoints doesn't do anything.

**Comment by JustinBack** [comment]
Have you restarted your browser after applying the overrides?


Can you also send me the extension logs? (Preferably the network requests from the extension)

**Comment by paulverbeke** [comment]
ok thanks a lot I managed to make the overrides work. Now ToSdr is working. Did you find a fix for this ? Thanks

**Comment by JustinBack** [comment]
The API https://api.tosdr.org/ is online. Existing installations should not be affected anymore

**Comment by rddunphy** [comment]
I'm still having this problem now - I haven't applied the overrides, though; are they still necessary? (FF 86.0, TOSDR 4.0.6)
