### ISSUE TITLE
The service is on tosdr.org with the right URL but the extension does not indicate that

### ISSUE THREAD

**Issue by pragmader** [tosdr/browser-extensions#74]
**Describe the bug**
Long time ago I added my personal blog as a service on tosdr.org. I recently revisited it and added some points.
Today I tried the official tosdr Chrome extension and the one from DuckDuckGo (which is also using the tosdr database). Both are displaying that the service is not registered in the tosdr database.

**To Reproduce**
1. Install the tosdr Chrome extension
2. Go to https://tosdr.org
3. Type `Pragmatic` in the search field and see this card

<img width="1127" alt="Screenshot 2021-02-25 at 16 54 16" src="https://user-images.githubusercontent.com/887952/109179454-326b0a00-778a-11eb-844b-749454875c8b.png">

4. Click `Visit Service`
5. Open the Chrome extension and see that the `Service is not rated yet`:

<img width="1904" alt="Screenshot 2021-02-25 at 17 00 16" src="https://user-images.githubusercontent.com/887952/109180262-f8e6ce80-778a-11eb-9a94-cc4644b02686.png">

**Expected behavior**
I expect that the extension displays the grade and the points from the tosdr.org database I have added for this web-site.

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Browser Chrome
 - Version 88.0.4324.192

**Additional context**
No overrides:
<img width="511" alt="Screenshot 2021-02-25 at 17 13 41" src="https://user-images.githubusercontent.com/887952/109181997-d48bf180-778c-11eb-92f9-8cd75320c9c2.png">
When I try to open the API domain I get this:
<img width="1752" alt="Screenshot 2021-02-25 at 17 16 32" src="https://user-images.githubusercontent.com/887952/109182444-3fd5c380-778d-11eb-8988-8bfbae2d0f3b.png">

- [x] I make sure not to use an API override
- [x] I make sure not to use a shield override
- [x] I make sure not to use an updatecheck override

**Comment by pragmader** [comment]
I suspect this is just a duplicate of https://github.com/tosdr/browser-extensions/issues/73

**Comment by JustinBack** [comment]
You can fix it yourself until the chrome release is out on chrome (it will take a long time for google to verify the update)

https://github.com/tosdr/browser-extensions/issues/73#issuecomment-782681403

![image](https://user-images.githubusercontent.com/40178814/109282945-7d366180-781e-11eb-9b26-98c9c043d0d9.png)

**Comment by JustinBack** [comment]
Or use https://github.com/tosdr/browser-extensions/releases/download/4.0.6/chrome.zip :-) Its essentially the release pending review

**Comment by pragmader** [comment]
@JustinBack thanks! I had to restart Chrome in order to force the data update but it eventually worked.
