### ISSUE TITLE
about:addons tab reopens itself frequently

### ISSUE THREAD

**Issue by kainino0x** [tosdr/browser-extensions#77]
**Describe the bug**
Frequently (I think every time tosdr updates, or maybe every time firefox updates, or every time both update at the same time, or something), it opens a tab in my browser to the tosdr "options" pane in `about:addons`. This started at least a few months ago.

**To Reproduce**
1. Install tosdr extension
2. Wait for tosdr update, or something
3. Restart firefox
4. Tab opens after a few seconds

**Expected behavior**

**Screenshots**

**Console Log**
If applicable, add console logs by enabling the `Debug` Option in `Options` -> `Advanced Mode`

**Desktop (please complete the following information):**
 - OS: Windows 10 version 20H2
 - Browser: Firefox
 - Version: 89.0a1 (2021-03-31) (64-bit)

**Extension (please complete the following information):**
- Version: 4.0.7
- Packed? yes

**Additional context**
I suspect this was supposed to happen *one* time to let me know that the options were there and could be set. But now it just happens all the time.

- [x] I make sure not to use an API override
- [x] I make sure not to use a shield override
- [x] I make sure not to use an updatecheck override

**Comment by JustinBack** [comment]
This is currently intended behavior on extension update and installation

https://github.com/tosdr/browser-extensions/blob/633dfef41541914692e393b6038b877eb690fb8a/src/background.js#L132-L136

**Comment by kainino0x** [comment]
Ah, I see. Unfortunately I think I will have to uninstall the extension then. It's very disruptive to have the options page open over whatever I'm doing, 30 seconds after opening the browser, every few days. (Also I remembered this happens in Chrome too.)

**Comment by JustinBack** [comment]
I see, well it should only happen when the extension updates (not every couple days, as we do not push updates that frequently).

I cannot reproduce this issue on my firefox installation, and it shouldnt happen in the first place (as you can see, only on installation and update of the extension). I'll look into this

**Comment by kainino0x** [comment]
It's very possible that it's happening more often for me because I use Firefox Nightly, so the _browser_ gets an update every day. I will pay closer attention to how often this happens and try to report back. Thanks for the help!
