### ISSUE TITLE
Experimental (un)support for Android

### ISSUE THREAD

**Issue by JustinBack** [tosdr/browser-extensions#78]
If you are running an Android device, you can make the ToS;DR Browser Extension work on a Nightly build!

https://docs.tosdr.org/guide/Browser-Extension-on-Android.166133777.html

Please note: This is unsupported, we currently do not have any plans on officially releasing an android version and bug reports regarding Android are invalid.

If you wish to make PRs that fix Android bugs, feel free to do so! We currently don't target Android so they are provided 'as-is', if it breaks, then it's not on the To-Do list to fix it.

**Comment by thebiblelover7** [comment]
Is it just me, or can I not open this?

**Comment by JustinBack** [comment]
> Is it just me, or can I not open this?

Good call, fixed link. https://docs.tosdr.org/guide/Browser-Extension-on-Android.166133777.html

**Comment by ptgms** [comment]
Now supported in new Extension!
