### ISSUE TITLE
https://twitter.com/i/status/1220825462500405250

### ISSUE THREAD

**Issue by Hassan92Wa** [tosdr/browser-extensions#80]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Console Log**
If applicable, add console logs by enabling the `Debug` Option in `Options` -> `Advanced Mode`

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

- [ ] I make sure not to use an API override
- [ ] I make sure not to use a shield override
- [ ] I make sure not to use an updatecheck override

**Comment by JustinBack** [comment]
User has been blocked from interacting with repositories.
